# Generated by Django 6.0.7 on 2026-08-02 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('farmer_location', models.CharField(max_length=200)),
                ('milk_purity', models.CharField(choices=[('LOW', 'Low'), ('MID', 'Medium'), ('GREAT', 'Great')], max_length=5)),
                ('truck', models.CharField(choices=[('TRUCK_A', 'Truck A'), ('TRUCK_B', 'Truck B')], max_length=10)),
                ('collection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collection_time'],
            },
        ),
    ]
