# Generated by Django 6.0.7 on 2026-08-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkrecord',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional notes about this milk collection', null=True),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='farmer_photo',
            field=models.ImageField(blank=True, help_text='Upload a photo of the farmer', null=True, upload_to='farmer_photos/'),
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='milk_certificate',
            field=models.FileField(blank=True, help_text='Upload milk quality certificate (PDF, JPG, PNG)', null=True, upload_to='certificates/'),
        ),
    ]
